### ISSUE TITLE
0.8.4 breaks with `#[validate]` attribute

### ISSUE THREAD

**Issue by luben** [GREsau/schemars#109]
Plain `#[validate]` is used to validate nested types (https://github.com/Keats/validator#nested). Schemars does not handle it and fails with
```
error: expected #[validate(...)]
   --> src/api/customer_model.rs:197:7
    |
197 |     #[validate]
    |       ^^^^^^^^
```

**Comment by GREsau** [comment]
Fixed in v0.8.5, thanks for the report!
