### ISSUE TITLE
Set regex for Array String items

### ISSUE THREAD

**Issue by goddtriffin** [GREsau/schemars#110]
For the following code:

```Rust
#[derive(Serialize, Deserialize, JsonSchema)]
pub struct Team {
    /// # Users
    /// A list of users.
    #[schemars(regex(pattern = r"^(.*)$"))]
    pub users: Vec<String>
}
```

This is the output I currently see for the `users` field:
```json
"users": {
    "title": "Users",
    "description": "A list users.",
    "type": "array",
    "items": {
        "type": "string"
    }
},
```
As you can see, the regex is simply getting omitted entirely.

What I would like to see is:
```json
"users": {
    "title": "Users",
    "description": "A list users.",
    "type": "array",
    "items": {
        "pattern": "^(.*)$",
        "type": "string"
    }
},
```
Since regex doesn't make sense for an `array`, it should bubble down to the contained `String` type.

I would also expect this to work when setting `length(max = 39)` on the `users` field, where it isn't applied to the array, but to the underlying String.

**Comment by lpturmel** [comment]
@GREsau is this request considered or for people that need this behaviour we would need to look into manual implementations?
