### ISSUE TITLE
Bug in Derive Macro

### ISSUE THREAD

**Issue by JeremyRubin** [GREsau/schemars#126]
See: https://github.com/rust-bitcoin/bitcoin_hashes/pull/135

Files:
[OUT.txt](https://github.com/GREsau/schemars/files/7748087/OUT.txt)
[OUT_Tests.txt](https://github.com/GREsau/schemars/files/7748090/OUT_Tests.txt)

Essentially the type somehow gets confused and outputs an array when it should pass through to a string.

Perhpas a discrepency in handling generic structs v.s. non generic?

**Comment by JeremyRubin** [comment]
This issue comes up after version 0.8.3

**Comment by ralpha** [comment]
Could you provide us with a bit more of an explanation and what exactly goes wrong?
Because I have no idea even to start with this. The linked issue does not describe the problem and the files you are very big.
So a better description is needed.

**Comment by GREsau** [comment]
@JeremyRubin As ralpha said, could you give more info about the bug you're encountering? The description you put in this issue is not clear

**Comment by GREsau** [comment]
If you're still encountering a problem and can describe what it actually is, feel free to reopen this (or open a new issue)
