### ISSUE TITLE
Override Associated Type Schema Generation in Impl

### ISSUE THREAD

**Issue by harrysolovay** [GREsau/schemars#127]
I have a trait, with a field that must implement `JsonSchema`.

```rs
trait Something {
  type MyField: JsonSchema;
}
```

I implement the trait for `MyStruct`, supplying––as the associated `MyField` type––a struct from another crate.

```rs
use some_crate::StructFromSomeCrate;

impl Something for MyStruct {
  type MyField = StructFromSomeCrate;
  //             ^
  //             the trait bound `MyField: JsonSchema` is not satisfied
}
```

The `StructFromSomeCrate` itself is very minimal.

```rs
pub struct StructFromSomeCrate {
  t: u64,
}
```

Is there a way for me to specify the Schema generation behavior within the impl block, as to avoid the bound un-met error?

**Comment by ralpha** [comment]
Hmm, I think you are mixing `structs` and `traits` a bit here.

So you want to have your own trait `Something` but for it to be able to have that trait it also needs `JsonSchema`.
This is what is called a [`Supertrait`](https://doc.rust-lang.org/rust-by-example/trait/supertraits.html) (other languages might call this "inheritance", that is similar but not exactly the same.)

You do it like this:
```rust
trait Something: JsonSchema {
  // ... additional functions you want tot add here
}
```
So this means if I do `impl Something for MyStruct {...}` then `MyStruct` also needs to implement `JsonSchema`.
So:
```rust
#[derive(JsonSchema)]
struct MyStruct {

}

impl Something for MyStruct {...}
```

----
Okay that hopefully explains it a bit. But I think you want to implement `JsonSchema` for a struct that is not part of your crate.
You can not do this and there are a few ways of solving this.
So we want `StructFromSomeCrate` to implement `JsonSchema`.

The trait `JsonSchema` comes from `schemars` (so not the current crate you are working in) and `StructFromSomeCrate` also comes from an other crate.
A way to solve this is to just implement a new struct or enum that wraps around the `StructFromSomeCrate`.
```rust
struct `WrapStructFromSomeCrate(StructFromSomeCrate);

impl JsonSchema for WrapStructFromSomeCrate {
   // ... functions here
   // See: https://github.com/GREsau/schemars/issues/119 for more info for manual implementation
}
```

There are other ways, but this is usually the easiest in my experience. For more info see: https://stackoverflow.com/a/32034744/2037998

If you have more questions let me know.

**Comment by harrysolovay** [comment]
Ah yes, it's likely I'm mixing up constructs of the language... I'm a "rustling," so to speak ;)

Manually implementing the trait worked! Thank you for your help @ralpha!

**Comment by ralpha** [comment]
Nice, and thanks for the reply. If you have more questions let me know.
