### ISSUE TITLE
Raw doc comments as descriptions

### ISSUE THREAD

**Issue by blake-mealey** [GREsau/schemars#129]
Hey, love the project!

I have read through #120 and #38 but I've still not found a solution to simply using the raw doc comments without any modification. I have some standard markdown comments including code blocks which get squished onto one line. I would also like to use some custom markdown syntax my docs provider supports. The best solution for me would be to simply have schemars use the raw doc comments without any modifications. As far as I can tell there is currently no solution to this?

Thanks

**Comment by ralpha** [comment]
I think the best way to get this done is to add a comment to https://github.com/GREsau/schemars/issues/120 or create a PR for the change.
https://github.com/GREsau/schemars/issues/120 Was more to get some feedback from users on this before making a decision and/or changing it.

> As far as I can tell there is currently no solution to this?

No there is no fix for this right now.

**Comment by GREsau** [comment]
_Finally_, as of schemars [v1.0.0-alpha.3](https://github.com/GREsau/schemars/releases/tag/v1.0.0-alpha.3), whitespace from doc comments is no longer collapsed when generating a schema's `description` 🙂
