### ISSUE TITLE
Problem using the chrono schemas

### ISSUE THREAD

**Issue by xylix** [GREsau/schemars#14]
I have code like this 

```rust
use schemars::JsonSchema;

#[derive(Serialize, Deserialize, JsonSchema, Clone, Debug)]
pub struct Event {
    pub id: Option<i64>,
    pub timestamp: DateTime<Utc>,
}
```

And I get the compiler error "the trait `schemars::JsonSchema` is not implemented for `chrono::DateTime<chrono::Utc>". Even though it seems to me like https://github.com/GREsau/schemars/blob/5bf8b3075354a690561a7b81fcd1ed7fd56d87bf/schemars/src/json_schema_impls/chrono.rs pretty clearly implements DateTime<Utc> among other DateTime<Tz> combos.

Is there some import I'm missing or anything I should try to debug?

**Comment by GREsau** [comment]
What does your Cargo.toml look like? Support for chrono (and other optional dependencies) must be enabled via a feature flag, e.g.
`schemars = { version = "0.6.5", features = ["chrono"] }`

**Comment by xylix** [comment]
Oh yes. Toggling the feature flag on fixed the problem. Sorry for the hassle :). I'm quite new to configuring Cargo.toml files
