### ISSUE TITLE
Custom keywords

### ISSUE THREAD

**Issue by clemens-msupply** [GREsau/schemars#146]
JSONSchema allows users to define custom keywords. Would it be possible to add support for it to schemars? e.g.

```rust
#[derive(JsonSchema)]
pub struct MyStruct {
    #[schemars(custom_keyword(name = "myKeyword", value = "some custom metadata"))]
    pub my_int: i32,
}
```
would generate:
```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "MyStruct",
  "type": "object",
  "required": [
    "my_int"
  ],
  "properties": {
    "my_int": {
      "type": "integer",
      "format": "int32",
      "myKeyword": "some custom metadata")
    },
  },
}
```

**Comment by ralpha** [comment]
This is currently possible though manual implementation. Not though the macro.
Manual implementation of struct example: #119
Use the [`extensions`](https://docs.rs/schemars/0.8.10/schemars/schema/struct.SchemaObject.html#structfield.extensions) field in the `SchemaObject`.

Adding support for it though macros might be added, but not any time soon I expect.

**Comment by mickvangelderen** [comment]
I'm looking to add custom metadata to properties as well, ideally in-line with the type definition through an attribute. I'm building a configuration tool on top of json schemas and want to indicate for various properties whether they should be visible by default or only for advanced users.

**Comment by GREsau** [comment]
This is now possible in schemars 1.0.0-alpha.3:

```rust
#[derive(JsonSchema)]
pub struct MyStruct {
    #[schemars(extend("myKeyword" = "some custom metadata"))]
    pub my_int: i32,
}
```

results in:
```json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "MyStruct",
  "type": "object",
  "properties": {
    "my_int": {
      "type": "integer",
      "format": "int32",
      "myKeyword": "some custom metadata"
    }
  },
  "required": [
    "my_int"
  ]
}
```
