### ISSUE TITLE
Where to implement for ZeroVec

### ISSUE THREAD

**Issue by sffc** [GREsau/schemars#156]
I am a maintainer of the [`zerovec`](https://crates.io/crates/zerovec) crate, and I am interested in adding `schemars` support.

Is it better to submit a PR to `schemars` adding a `zerovec` feature alongside the many other collections components features, or is it better to make `schemars` an feature on `zerovec` instead?

**Comment by ralpha** [comment]
The last, make `schemars` a feature in `zerovec`.
You can treat is similarly to `serde`.

**Comment by sffc** [comment]
Thanks; will move this to https://github.com/unicode-org/icu4x/issues/2118.
