### ISSUE TITLE
JsonSchema for a struct in different crate

### ISSUE THREAD

**Issue by marirs** [GREsau/schemars#158]
Hi,
I'm not sure if this is answered before, as I did search before asking the question. I have a Struct from a different crate within my struct where i'm using JsonSchema. How can I use it. Kindly help.

```
#[derive(Debug, Serialize, Deserialize, Clone, JsonSchema)]
struct MyStruct {
  from_crate1: CrateStruct,
}
```

During compile, I get error because of CrateStruct begin in another crate.

**Comment by ralpha** [comment]
`CrateStruct` in this case requires the trait `JsonSchema` (and others). But if it is not implemented for it there are only 2 places this can be implemented in rust.
The crate where the structs is created (So the external crate you use).
Or
The crate the trait is implemented (so `schemars`).

So in short. Ask the original crate to implement `JsonSchema` for the struct. (best done under a feature flag).
If you want to know more about why and the current policy see: #131

You can also do a total manual implementation. For this look at: #119 and #125

**Comment by marirs** [comment]
Thank you
