### ISSUE TITLE
Support base64 blobs, or provide an example

### ISSUE THREAD

**Issue by ctron** [GREsau/schemars#160]
I am having troubles figuring out how to deal with base64 encoded blobs.

This can be used with serde, using the `base64-serde` crate. However, I would also need to add some metadata for schemars.

I can seem to set the type to `string`:

```rust
base64_serde_type!(Base64Standard, STANDARD);

#[derive(
    Clone, Debug, serde::Deserialize, serde::Serialize, schemars::JsonSchema,
)]
pub struct Foo {
  #[serde(with = "Base64Standard")]
  #[schemars(with = "String")]
  pub blob: Vec<u8>
}
```

However, I can't seem to set the `format` or `contentEncoding`.

**Comment by ahl** [comment]
We did this with a hand-rolled `JsonSchema` implementation: https://github.com/oxidecomputer/omicron/blob/17485e8bc05a0e50d5223a09094c9b90b677d55c/nexus/src/external_api/params.rs#L404-L482

Note that while this is applicable for our use case with OpenAPI v3.0.3, it would be good to see schemars updated to include `contentEncoding` and `contentMediaType`.

**Comment by GREsau** [comment]
The easiest way to achieve this in schemars 1.0.0-alpha.3 is with the `extend attribute" e.g.

```rust
#[derive(JsonSchema)]
pub struct Foo {
    #[schemars(with = "String", extend("contentMediaType" = "application/octet-stream", "contentEncoding" = "base64"))]
    pub blob: Vec<u8>,
}
```
