### ISSUE TITLE
Schema customization

### ISSUE THREAD

**Issue by MikailBag** [GREsau/schemars#173]
Sometimes user wants not to override schema generation, but to post-process it.
One possible case is to add non-standard extensions, e.g. `x-kubernetes-validations` extension can be used to CustomResourceDefinition-s to add programmatic validation rules.

Proposed solution: add a new `customize_with` attribute which can be applied to the whole `derive`-ing container, e.g.
```rust
#[derive(JsonSchema)]
#[schemars(customize_with = "customize")]
struct Foo {
   // ...
}

// this function will be called after schema for Foo is generated, and it can modify returned schema
fn customize(schema: &mut schemars::schema::Schema) {
    // something like schema.extensions.insert("x-my-custom-extension", ...) here.
}
```

**Comment by GREsau** [comment]
This is implemented in schemars 1.0.0-alpha.3 with [the `transform` attribute](https://graham.cool/schemars/deriving/attributes/#transform):

```rust
#[derive(JsonSchema)]
#[schemars(transform = customize)]
struct Foo {
    // ...
}

// this function will be called after schema for Foo is generated, and it can modify returned schema
fn customize(schema: &mut schemars::Schema) {
    schema
        .ensure_object()
        .insert("x-my-custom-extension".to_owned(), json!("whatever"));
}
```

Or for the common case where you just want to add a single property, you can instead use [the `extend` attribute](https://graham.cool/schemars/deriving/attributes/#extend):
```rust
#[derive(JsonSchema)]
#[schemars(extend("x-my-custom-extension" = json!("whatever")))]
struct Foo {
    // ...
}
```
