### ISSUE TITLE
Improve interop between schemars and progenitor

### ISSUE THREAD

**Issue by DanielJoyce** [GREsau/schemars#174]
progenitor is a rust based tool to generate clients from openapi specifications

The problem is when a struct has a field like this:

```
    #[schemars(range(min = 400, max = 599))]
    pub code: u16,
```

Schemars generates a file where the max and min are 'floats' with trailing zeros

```
"code": {
  "description": "The HTTP error code.",
  "type": "integer",
  "format": "uint16",
  "maximum": 599.0,
  "minimum": 400.0
},
```

progenitor rejects this 

https://github.com/oxidecomputer/progenitor/issues/194

Perhaps when a field is annotated with range and it's a int field, the max and min could be emitted without a trailing `.0`?

**Comment by GREsau** [comment]
I believe this is fixed in schemars 1.0, since all numeric properties are serialized as `serde_json::Number` which doesn't include trailing `.0` for integers
