### ISSUE TITLE
Array's `items` being set to `true`

### ISSUE THREAD

**Issue by jpage-godaddy** [GREsau/schemars#185]
We're seeing issues where schemars output is creating schemas for JSON arrays where `items` is being set to `true`.

```json
{
  "type": "object",
  "required": [
    "userIds"
  ],
  "properties": {
    "userIds": {
      "type": "array",
      "items": true
    }
  }
}
```

From what I can tell in `JSONSchema`, this is not allowed. Here's a struct that is causing that type of output:

```rust
#[derive(Clone, Debug, Deserialize, Eq, PartialEq)]
#[serde(rename_all = "camelCase")]
#[cfg_attr(feature = "schemars", derive(JsonSchema))]
pub struct Sample {
    pub user_ids: Vec<Value>,
}
```

We have cases like this where we need an Array of _any valid JSON value_. If we use `Vec<String>` things work fine and we get `"items": { "type": "string" }`.

Is there any way to generate an `array` schema with open-ended item types, or alternatively a union of types would also work.

**Comment by chanced** [comment]
That's valid json schema.

`true` expands to `{}` which means all types pass.

**Comment by jpage-godaddy** [comment]
OK, thanks. I did finally see in the spec where that's allowed.
