### ISSUE TITLE
Runtime error when generating a schema for a complex tagged enum

### ISSUE THREAD

**Issue by rklaehn** [GREsau/schemars#2]
First of all, awesome library! I was dabbling with writing something similar and was very happy that this library exists!

I ran into an issue when trying to generate a schema for a tagged enum. See reproducer below.

```rust
use serde::{Serialize, Deserialize};
use schemars::{JsonSchema, schema_for};

#[derive(Debug, Serialize, Deserialize, JsonSchema)]
pub struct BValues {
    a: u32,
    b: u32,
}

#[derive(Debug, Serialize, Deserialize, JsonSchema)]
#[serde(tag = "type")]
pub enum Foo {
    #[serde(rename = "a")]
    A,
    #[serde(rename = "b")]
    B(BValues),
}


fn main() -> Result<(), Box<dyn std::error::Error>> {
    let schema = schema_for!(Foo)?;
    println!("{}", serde_json::to_string_pretty(&schema)?); // fails
    Ok(())
}
```

This produces the following error:

```
Error: JsonSchemaError { msg: "Only schemas with type `object` can be flattened.", schema: Ref(Ref { reference: "#/definitions/BValues" }) }
```

**Comment by GREsau** [comment]
Thanks for the report!

I've committed a fix, it should be in v0.1.9 - I'll leave another comment here when it's available on crates.io

**Comment by GREsau** [comment]
And schemars 0.1.9 is up!

Thanks again for the report, let me know if you find any more issues

**Comment by rklaehn** [comment]
That was fast! Thanks a lot.
