### ISSUE TITLE
Is this crate unmaintained?

### ISSUE THREAD

**Issue by H2CO3** [GREsau/schemars#225]
I have seen several bug reports and feature requests during the last few months on this repository. However, they received zero interaction from the author.

Should we consider this crate unmaintained/deprecated/defunct?

**Comment by jayvdb** [comment]
Is there any urgent fixes needed? If so, ping them on the issue/PR, or email them. If not, a few months without maintainer activity on this project isnt enough to suggest it is unmaintained or defunct.  They are active on personal projects.

**Comment by ralpha** [comment]
I keep an eye on this project too from time to time. I have not done many contributions here, but know how it works. So could do updates/maintenance if needed. I maintain https://github.com/GREsau/okapi (created by the same author) for a little while now, after having talked with GREsau a while back. Which relies heavily on this crate.

So if there is something that needs urgent patching, I can do it and would be able to get done in a few weeks. But If not urgent it might come down to finding some time (whenever that comes) to do a lot of maintenance all at once and go though issues and PRs.

And last release was 4 months ago. Which is also not that long ago. So no need to worry.

But like stated above most of us don't always have the time to dedicate to these projects. So help is always welcome, in the form of investigating issues, reviewing and creating PRs, ... (That will make it easier to add as many fixes and features in next release as possible.)

**Comment by filips123** [comment]
I don't think there are things that need urgent patching, but there are quite a lot of open PRs that should probably be reviewed. Most of them are related to adding support for third-party libraries, so it would be nice if at least the policy regarding this (#131) could be clarified. Although the policy seems to prefer that libraries themselves implement the required types, `schemars` still hasn't reached 1.0 (#112), which might block some libraries from implementing `schemars` support.

So, ideally, `schemars` should implement things mentioned in #112 and then clarify how libraries should implement support for it. I know this is quite a lot of work and probably won't happen soon though... So, in the short term, at least reviewing the existing PRs (even it is just "This should be implemented in that third-party library") would be nice.

Specifically, I would like support for ULID v1 (#73 exists but it's for older version) and `serde_with` (there is #198 which is also for older version, but they seem to be waiting for any confirmation from maintainers). But I think other PRs should probably also be reviewed.

**Comment by GREsau** [comment]
It's a fair question, sorry for my radio silence over the past few months...

The short answer is: no, schemars should not be considered unmaintained. Now that I've fixed the CI I plan on working through the backlog of PRs over the next couple of weeks.

The good news is that I haven't been _completely_ idle - I've done some planning and prototyping for some changes that will be required for an eventual v1.0, and I hope to write up some corresponding API proposals soon to gather feedback from the community 🙂
