### ISSUE TITLE
Missing "$id" field on root schema

### ISSUE THREAD

**Issue by PierreBeucher** [GREsau/schemars#229]
JSON specifications defines an optional `$id` for root schema. It's not required but recommended as best practices. See for instance: https://json-schema.org/understanding-json-schema/structuring.html#id

Currently generating a schema, even with custom config, does not generate `$id` field. However it seems to exists on [`Metadata` internal struct](https://github.com/GREsau/schemars/blob/386e3d7f5ac601795fb4e247291bbef31512ded3/schemars/src/schema.rs#L263). 

Is there a way to specify `$id` somehow?

**Comment by AntoineGS** [comment]
I am also trying to generate a schema with the `$id` field (for [SchemaStore](https://github.com/SchemaStore/schemastore)). Does anyone have a workaround? (Other than inserting the line after running this crate).

**Comment by sf1tzp** [comment]
I found that something like this works:
```
    let mut schema = schema_for!(MyStruct);
    let metadata = schema.schema.metadata.as_mut().unwrap();
    metadata.id = Some(String::from("MyProject/MyStruct"));
    fs::write(output_path, serde_json::to_string_pretty(&schema).unwrap()).unwrap()
```
Results in:
```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "MyProject/MyStruct",
  ...
}
```
