### ISSUE TITLE
Incorrect Schema Generated for Response with Tuple

### ISSUE THREAD

**Issue by MicaiahReid** [GREsau/schemars#230]
Hi! I created [this issue](https://github.com/GREsau/okapi/issues/127) over on the okapi repo, but it looks to actually be an issue with schemars. 

This example has a simple struct with a tuple inside:

```rust
use schemars::{schema_for, JsonSchema};

#[derive(serde::Serialize, JsonSchema, Debug)]
struct Response {
    reply: (u64, u64),
}
fn main() {
    let schema = schema_for!(Response);
    println!("{}", serde_json::to_string_pretty(&schema).unwrap());
}
```

This generates the following schema:
```JSON
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Response2",
  "type": "object",
  "required": [
    "reply"
  ],
  "properties": {
    "reply": {
      "type": "array",
      "items": [
        {
          "type": "integer",
          "format": "uint64",
          "minimum": 0.0
        },
        {
          "type": "integer",
          "format": "uint64",
          "minimum": 0.0
        }
      ],
      "maxItems": 2,
      "minItems": 2
    }
  }
}
```
However, I think it should instead be:
```JSON
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Response2",
  "type": "object",
  "required": [
    "reply"
  ],
  "properties": {
    "reply": {
      "type": "array",
      "items": {
        "type": "integer",
        "format": "uint64",
        "minimum": 0.0
      },
      "maxItems": 2,
      "minItems": 2
    }
  }
}
```

**Comment by GREsau** [comment]
What makes you say it's incorrect? For draft-07 schemas:
> If "items" is a schema, validation succeeds if all elements in the array successfully validate against that schema.
>
> If "items" is an array of schemas, validation succeeds if each element of the instance validates against the schema at the same position, if any.

So in your case, both of those schemas are actually equivalent, but schemars uses the "array of schemas" style, mainly to support the more general case where the tuple may have different elements. e.g. if the tuple were of type `(u64, String)`, the schema would need to be:
```javascript
{
  /* snip */
  "properties": {
    "reply": {
      "type": "array",
      "items": [
        {
          "type": "integer",
          "format": "uint64",
          "minimum": 0.0
        },
        {
          "type": "string"
        }
      ],
      "maxItems": 2,
      "minItems": 2
    }
  }
}
```

**Comment by GREsau** [comment]
In the latest JSON schema version (draft 2020-12), "items" does have to be a single JSON schema, and tuples instead need to use the new "prefixItems" keyword - but the latest version schemars currently supports is draft 2019-09, which still supports "items" arrays.

Closing this issue as I believe the current behaviour is correct - feel free to reopen if you disagree
