### ISSUE TITLE
chrono test error

### ISSUE THREAD

**Issue by dishmaev** [GREsau/schemars#24]
Hi

before run test i added in schemars/Cargo.toml
[dev-dependencies]
chrono = { version = "0.4" }

and removed
[[test]]
name = "chrono"
required-features = ["chrono"]

run (my OS Debian GNU/Linux 10)
cargo test chrono

result

schemars/tests/chrono.rs:9:5
  |
9 |     date_time: DateTime<Utc>,
  |     ^^^^^^^^^ function or associated item not found in `chrono::datetime::DateTime<chrono::offset::utc::Utc>`
  |
  = note: the method `add_schema_as_property` exists but the following trait bounds were not satisfied:
          `&chrono::datetime::DateTime<chrono::offset::utc::Utc> : schemars::JsonSchema`
          `&mut chrono::datetime::DateTime<chrono::offset::utc::Utc> : schemars::JsonSchema`

**Comment by GREsau** [comment]
I'm not really sure what you're trying to do, but if you want `JsonSchema` to be implemented on chrono types without requiring the chrono feature flag or optional dependency to be specified, then you'd need to remove the `#[cfg(feature = "chrono")]` attribute here:
https://github.com/GREsau/schemars/blob/726860cb8eb9d9f9bba516b6488d28c82c91a01e/schemars/src/json_schema_impls/mod.rs#L49-L50

But for that to work, you'd need chrono to be included as a non-optional dependency, not a dev-dependency.

**Comment by GREsau** [comment]
If all you want to do is run the chrono tests, you can do this by including the chrono feature when you run the tests:
`cargo test --features chrono chrono`

However you must run command that inside the schemars directory, not in the repo's top-level directory. This is because `--feature` only works when run from a crate directory, not a cargo workspace directory.

**Comment by dishmaev** [comment]
in schemars/Cargo.toml not found feature "chrono"

[features]
impl_json_schema = []
# derive_json_schema will be removed in a later version
derive_json_schema = ["impl_json_schema"]

i added this feature in my Cargo.toml
schemars = { version = "0.7", features = ["chrono"] }

and now it's ok

thanks
