### ISSUE TITLE
Support for no_std

### ISSUE THREAD

**Issue by kvinwang** [GREsau/schemars#254]
I came across this fantastic crate. However, some of my crates are no_std. It would be great if schemars could support no_std compatibility. Otherwise, we'll have to use `#[cfg_attr(feature = "std", derive(JsonSchema))]` and pass around the `std` feature in Cargo.toml files everywhere.

**Comment by GREsau** [comment]
This is now available in schemars 1.0.0-alpha.5 🙂 

You can use it by disabling the new `std` feature flag, e.g.

```toml
schemars = { version = "1.0.0-alpha.5", default-features = false }
```

Or in the likely event you still want to `derive(JsonSchema)`:

```toml
schemars = { version = "1.0.0-alpha.5", default-features = false, features = ["derive"] }
```
