### ISSUE TITLE
Support for omitting fields from the schema

### ISSUE THREAD

**Issue by untitaker** [GREsau/schemars#27]
I would like schemars to honor `serde(skip)` and `schemars(skip)` to be able to omit internal datastructures. Ex:

```rust
#[derive(JsonSchema)]
struct Foo {
    #[schemars(skip)]
    bar: String
}
```

would generate a schema against which the input `{}` validates.

**Comment by GREsau** [comment]
This is already implemented - when I run
```rust
use schemars::{schema_for, JsonSchema};

#[derive(JsonSchema)]
struct Foo {
    #[schemars(skip)]
    bar: String
}

fn main() {
    let schema = schema_for!(Foo);
    println!("{}", serde_json::to_string_pretty(&schema).unwrap());
}
```

It outputs:
```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Foo",
  "type": "object"
}
```

Have you encountered a case where this doesn't happen?

**Comment by untitaker** [comment]
You're right it does, sorry for the noise. The actual issue I am running into is that all of the schemas generated by schemars do not have additionalProperties set to `false`, so this attempt failed:

```rust
#[derive(JsonSchema)]
struct Foo {
    #[schemars(skip)]
    #[serde(other)]
    extra_data: ...
}
```

Is there a way to generically set the default of additionalProperties?

**Comment by GREsau** [comment]
The `#[serde(other)]` attribute is not valid in your example. If you're trying to add a field that contains all additional properties when desrializing, then this would be done with the `#[serde(flatten)]` attribute as documented here: https://serde.rs/attr-flatten.html#capture-additional-fields

And in this case, `additionalProperties` will be set to true, e.g.
```rust
#[derive(JsonSchema)]
struct Foo {
    bar: String,
    #[serde(flatten)]
    extra: HashMap<String, Value>,
}
```
Outputs:
```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Foo",
  "type": "object",
  "required": [
    "bar"
  ],
  "properties": {
    "bar": {
      "type": "string"
    }
  },
  "additionalProperties": true
}
```

Unless you added `#[schemars(skip)]` to the `extra` field, in which case `additionalProperties` would not be set.

**Comment by GREsau** [comment]
Schemars doesn't set `additionalProperties` to false in derived schemas, mainly because serde allows unknown properties by default. 

If you have a struct with [`#[serde(deny_unknown_fields)]`](https://serde.rs/container-attrs.html#deny_unknown_fields), then it would make sense for the schema to set `additionalProperties` to false. I've planned on implementing that for a while (hence [this comment](https://github.com/GREsau/schemars/blob/master/schemars_derive/src/attr/schemars_to_serde.rs#L11)!), it's just one of the things I haven't got around to and no-one's asked for

**Comment by untitaker** [comment]
Thanks, I did mean `flatten`. The real background is that we are using a custom deserialization library other than serde and I was trying to keep the examples short.

I am a bit confused why you are either setting `additionalProperties=true` vs omitting it, as omission is the same thing as setting it to true afaik.

In any case `deny_unknown_fields` across all structs is likely closest to what I would need as our deserialization framework's default behavior diverges from serde here.

**Comment by untitaker** [comment]
I'm going to close this since the underlying feature I am missing is already tracked in sourcecode and this thread is quite long-winded.
