### ISSUE TITLE
Example for JsonSchema without definition references

### ISSUE THREAD

**Issue by notdanilo** [GREsau/schemars#271]
How can I generate a JsonSchema without `$ref`s and `definitions`?

And what is schemars generate for serde_json::Value?

```rust 
#[derive(Serialize, Deserialize, JsonSchema)]
/// The parameters for the multi_call function
struct MultiCallParameters {
    /// The function calls to make
    calls: Vec<FunctionCall>
}

#[derive(Clone, Serialize, Deserialize, JsonSchema)]
/// A function call
pub struct FunctionCall {
    /// The name of the function
    pub name: String,
    /// The arguments to the function
    pub arguments: serde_json::Value
}
```

This is becoming extremely necessary now that Large Language Models are using JsonSchemas (without external definition references) for function calls.

**Comment by notdanilo** [comment]
I found a way to do it in the examples.

**Comment by stewartadam** [comment]
> How can I generate a JsonSchema without `$ref`s and `definitions`?

@notdanilo were you able to do this? I'm trying to do the same and not finding it in the current docs.

**Comment by notdanilo** [comment]
@stewartadam this is how I enforce OpenAI's subset https://github.com/sensorial-systems/ligen/blob/main/ecosystem/llm/parser/src/schema/mod.rs
