### ISSUE TITLE
Annotate a field so it is both `required` and `default`

### ISSUE THREAD

**Issue by Shelim** [GREsau/schemars#276]
I was unable to find a way to annotate a field, so it both:

 - Does have a default value
 - Is still required

Reasoning: I am using Vscode as JSON editor, and its intelisense can automatically put the default value of the JSON field from schema when it is created. But the field must be present in data, for the actual loader.

Visual reference (field "Name" has a default value of "Someone") - and I want it to be still required:
![Code_-_Insiders_TRzP0cpWx7](https://github.com/GREsau/schemars/assets/4707644/4aa4baa0-8718-467f-8641-6053c6c6e7a6)

**Comment by GREsau** [comment]
The easiest way to achieve this in schemars 1.0.0-alpha.3 is by using the `extend` attribute, which can be used to set/override any property on the schema including `default`:

```rust
#[derive(JsonSchema)]
pub struct Author {
    #[schemars(extend("default" = "Someone"))]
    pub name: String,
}
```

produces:
```json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Author",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "default": "Someone"
    }
  },
  "required": [
    "name"
  ]
}
```
