### ISSUE TITLE
Enums in Swagger UI

### ISSUE THREAD

**Issue by ralpha** [GREsau/schemars#28]
Swagger UI has a bug, ... already for 3 years. Were is handles `enum` without a `type`poorly.
See: https://github.com/swagger-api/swagger-ui/issues/3761
A quick fix for this is adding a type: string item to the schema.
```json
"RegionType": {
  "description": "...",
  "type": "string",   <----Add_this_line
  "enum": [
    "Swamp",
    "Desert",
    "...",
    "Unknown"
  ]
}
```
Adding the line above will change the output in Swagger UI from: 
![Screenshot from 2020-05-12 00-24-07](https://user-images.githubusercontent.com/2608639/81618357-76517600-93e7-11ea-8be0-dfd7cbac7b86.png)
To This:
![Screenshot from 2020-05-12 00-24-26](https://user-images.githubusercontent.com/2608639/81618377-7fdade00-93e7-11ea-9fc2-c8e85fde024c.png)

It would be cool if this can be fixed here.
Btw love this crate and the others you made. (I'm also using okapi and rocket_okapi.)

**Comment by GREsau** [comment]
Thanks for raising this, it's now fixed in v0.7.4 🙂
