### ISSUE TITLE
Compatibility with json-schema.org ?

### ISSUE THREAD

**Issue by wiiznokes** [GREsau/schemars#284]
It might be a silly question, but is this crate compatible with https://json-schema.org/specification ?

**Comment by SwannHERRERA** [comment]
Yes, the purpose of this crate is to generate a json that validate the data and the structure that you want to build. I don't know what "draft" and version they are using, sometime I struggle to find the correct way to reproduce a pattern.

**Comment by GREsau** [comment]
As @SwannHERRERA says, this crate generates schemas according to the JSON Schema specification (https://json-schema.org/specification). By default, the latest version of schemars (1.0.0-alpha.7) uses the "draft 2020-12" version of JSON Schema, which is currently the latest available version of the JSON Schema, but this may change in a future schemars version.

**Comment by wiiznokes** [comment]
It would be nice to add a tab in the readme that match `schemars` version to compatible json-schema version. 
I recently started a project `0.8` but now, i've got errors, and i'm wondering if its a version mismatch

**Comment by wiiznokes** [comment]
Ok, so `0.8` is compatible with `draft7`
