### ISSUE TITLE
Switch to indexmap 2 for the `preserve_order` feature 

### ISSUE THREAD

**Issue by sandhose** [GREsau/schemars#285]
The `preserve_order` feature currently uses `indexmap@1`. It should probably use `indexmap@2` instead?
In my dependency tree, `schemars` is the only remaining dependency using `indexmap@1` instead of `indexmap@2`

**Comment by GREsau** [comment]
This is fixed in schemars 1.0.0-alpha.1+ by nature of the `preserve_order` now just enabling the corresponding feature in serde_json
