### ISSUE TITLE
Sponsor Page?

### ISSUE THREAD

**Issue by DonIsaac** [GREsau/schemars#336]
Have you considered adding a Sponsorship page? Would love to help fund development for this crate. Oxc relies on it pretty heavily.

**Comment by GREsau** [comment]
Well, if you insist 😄 

I've created a sponsorship profile at https://github.com/sponsors/GREsau - if you do choose to contribute, it will be much appreciated!

**Comment by DonIsaac** [comment]
Excited for 1.0, keep it up!
