### ISSUE TITLE
Compatibility with Serde_repr

### ISSUE THREAD

**Issue by ThouCheese** [GREsau/schemars#35]
dtolnays Serde_repr allows people to generate more compact json representations of Rust's enums. Currently when schemars generates a schema for an enum annotated with `Serde_repr`, it generates an incorrect schema. 
```rust
#[derive(serde_repr::Serialize_repr, schemars::JsonSchema)]
#[repr(u8)]
struct Kind {
    One = 1,
    Two = 2,
    NotThree = 4,
}
```
The resulting schema looks like:
```json
"Kind": {
  "type": "string",
  "enum": [
    "One",
    "Two",
    "NotThree"
  ]
},
```
For the person using the documentation this is confusing, since they will read the documentation and expect strings, but they will receive integers. The correct output would be:
```json
"Kind": {
  "type": "string",
  "enum": [
    1,
    2,
    4
  ]
},
```

**Comment by GREsau** [comment]
I'd rather not assume that the presence of `#[repr(u8)]` means that the enum will be serialized as a string because that may not be the case. So I think to handle this reliably we'd need to either add a new attribute e.g. `#[schemars(u8)], or a different derive macro e.g.
```rust
#[derive(serde_repr::Serialize_repr, schemars::JsonSchema_repr)]
#[repr(u8)]
struct Kind {
    One = 1,
    Two = 2,
    NotThree = 4,
}
```

I think I prefer the `JsonSchema_repr` solution as it nicely mirrors `Serialize_repr`

Do you have any thoughts on this?

**Comment by ThouCheese** [comment]
Hmm I think it would be hard to detect whether the enum implements Serialize or Serialize_repr, so I think that a seperate macro is needed. Just going by the repr(u8) is indeed not good enough, so that sounds good!

**Comment by GREsau** [comment]
This is implemented and will be in the next version - see https://graham.cool/schemars/examples/8-enum_repr/ for an example

**Comment by ThouCheese** [comment]
Thanks for this feature @GREsau !

**Comment by GREsau** [comment]
Implemented and published! https://crates.io/crates/schemars/0.8.2
