### ISSUE TITLE
Can't use `#[serde(with = "rust_decimal::serde::arbitrary_precision")]` when `#[derive(JsonSchema)]` is used

### ISSUE THREAD

**Issue by elipp** [GREsau/schemars#350]
Consider the following struct:

```
#[derive(Deserialize, Serialize, JsonSchema)]
struct SomeStruct {
    #[serde(with = "rust_decimal::serde::arbitrary_precision")]
    field: Decimal,
}
```

Compilation fails with:
error[E0573]: expected type, found module `rust_decimal::serde::arbitrary_precision`

How can I make that work? Ideally, I'd like this Decimal field to show up as a JSON number in the spec.

**Comment by elipp** [comment]
I did try the `#[serde_as]` macro from the `serde_with` crate with `feature=schemars_0_8` enabled, but couldn't figure out how.

**Comment by elipp** [comment]
Ended up just manually `impl JsonSchema`ing (an example can be found [on the schemars docs](https://docs.rs/schemars/latest/schemars/trait.JsonSchema.html).

**Comment by Eligioo** [comment]
Looks like a duplicate of #89

**Comment by elipp** [comment]
@Eligioo Thanks, closing this one!
