### ISSUE TITLE
how to generate json schema from serde_json::value::Value?

### ISSUE THREAD

**Issue by clojurians-org** [GREsau/schemars#47]
i want to generate json schema from dynamic json value.
i don't know whether schemars support this function.

```rust
    let data = r#"
        {
            "name": "John Doe",
            "age": 43,
            "phones": [
                "+44 1234567",
                "+44 2345678"
            ]
        }"#;
    let v: Value = serde_json::from_str(data)? ;
```

**Comment by ahl** [comment]
Pretty sure this library doesn't handle that case. It's great for Type -> JsonSchema, but you're deriving the schema from the data rather than from the type. That said, it would be pretty straightforward to build a function to extract a schema from the Value.

**Comment by GREsau** [comment]
This functionality isn't currently implemented, but I would like to do something like this. And actually I'd prefer to widen it to allow generating a schema from an instance any type that implements `serde::Serialize` (which includes `serde_json::value::Value`). Then you can get a schema from any value that can be serialized, even if it doesn't implement `JsonSchema`. And there would be more type information available than if it was done via a `Value`, allowing a richer schema.

**Comment by GREsau** [comment]
This will be possible in the next version - this code:
```rust
let data = r#"
        {
            "name": "John Doe",
            "age": 43,
            "phones": [
                "+44 1234567",
                "+44 2345678"
            ]
        }"#;
let v: serde_json::Value = serde_json::from_str(data)?;
let schema = schema_for_value!(v);
println!("{}", serde_json::to_string_pretty(&schema)?);
```

Produces this schema:
```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "examples": [
    {
      "age": 43,
      "name": "John Doe",
      "phones": [
        "+44 1234567",
        "+44 2345678"
      ]
    }
  ],
  "type": "object",
  "properties": {
    "age": {
      "type": "integer"
    },
    "name": {
      "type": "string"
    },
    "phones": {
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  }
}
```

**Comment by GREsau** [comment]
`schema_for_value!(...)` won't be limited to `serde_json::Value`s - as I said in my earlier comment, any type that implements `serde::Serialize` can have a schema generated from a value, e.g. [from_value.rs](https://github.com/GREsau/schemars/blob/master/schemars/examples/from_value.rs) / [from_value.schema.json](https://github.com/GREsau/schemars/blob/master/schemars/examples/from_value.schema.json)

**Comment by GREsau** [comment]
Implemented and published! https://crates.io/crates/schemars/0.8.2

**Comment by jmagnusson** [comment]
Nice work @GREsau 😀👍🏻
