### ISSUE TITLE
Forbid unsafe code

### ISSUE THREAD

**Issue by ralpha** [GREsau/schemars#53]
`schemars` does not seem to use unsafe code, which is very good :)

To prevent this from ever happening, add following line to the top:
```rust
#![forbid(unsafe_code)]
```
of https://github.com/GREsau/schemars/blob/master/schemars/src/lib.rs
and https://github.com/GREsau/schemars/blob/master/schemars_derive/src/lib.rs

This will make the package green in 
https://github.com/rust-secure-code/cargo-geiger

**Comment by GREsau** [comment]
Good idea!

Implemented in 40d9bfd5177cc581f7e261c1806279eaf250eaa1
