### ISSUE TITLE
Add optional dependency/handling of url

### ISSUE THREAD

**Issue by luben** [GREsau/schemars#58]
The https://crates.io/crates/url crate seems to be the common standard through the ecosystem. It would be nice if it could be handled so that we can generate schemas for structs containing URLs.

I would expect this code to compile:

```rust
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use url::Url;

#[derive(JsonSchema, Serialize, Deserialize)]
pub struct Foo {
  pub uri: Url
}
```

though currently it fails with:
```
   --> src/model/api.rs:104:14
    |
104 |     pub uri: Url,
    |              ^^^ the trait `schemars::JsonSchema` is not implemented for `url::Url`
    |
    = note: required by `schemars::JsonSchema::add_schema_as_property`
```

**Comment by luben** [comment]
BTW, if you agree it's worth adding, I can try implementing it behind feature flag.

**Comment by GREsau** [comment]
Implemented and published! https://crates.io/crates/schemars/0.8.2
