### ISSUE TITLE
support for k8s "structural" schemas

### ISSUE THREAD

**Issue by cassandracomar** [GREsau/schemars#84]
docs: https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#specifying-a-structural-schema

currently, schemars generates schemas that are rejected as non-structural for complex enumerations of the type:
```rust
enum MyType {
    Variant1(Variant1),
    Variant2(Variant2),
...
    VariantN(VariantN),
}
```

where `Variant1`, `Variant2`, ..., `VariantN` are themselves structs. as this is a common pattern to lift enumeration variants into the rust type system, this happens all over the place in idiomatic rust code. moreover, the structs generated by the `k8s-openapi` crate necessarily produces complex enums of this sort in the process of translating the k8s api types.

there may also be other kinds of structs that produce non-structural schemas and I'll document them here as I find them.

I'm happy to take on implementation of a fix for this issue if I can get some direction on how best to do so. is a crate-level feature a suitable way to toggle how enums are handled? this makes the update to k8s-openapi more straightforward but I notice that most features of this sort are handled as per-type macro arguments, currently.

**Comment by GREsau** [comment]
I don't really want to implement workarounds for kubernetes-specific restrictions into schemars. I think implementing a `Visitor` to transform a generated schema into the desired structure is the best way to get around this - exactly as @nightkr did 😄

**Comment by nightkr** [comment]
I can still see there being value to the idea of separating the structure from the validation rules outside of the context of K8s, but it's also valid to not want to commit to supporting both strategies.
